version: '3.6'

services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: game
    restart: always
    environment:
      MYSQL_DATABASE: game
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

    volumes:
      - ./init:/docker-entrypoint-initdb.d