import Navbar from '@/components/navbar/navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <header>
            <Navbar/>
          </header>
        {children}
        </main>
      </body>
    </html>
  )
}
